"""Async candidate buffer protocol."""
from __future__ import annotations

from typing import Protocol

from app.runtime.models import AgentEvent


class CandidateBufferProtocol(Protocol):
    async def append(self, event: AgentEvent) -> None: ...
    async def pending(self, session_id: str, workspace_id: str | None = None) -> list[AgentEvent]: ...
    async def drain(self, session_id: str, workspace_id: str | None = None) -> list[AgentEvent]: ...
    async def size(self, session_id: str, workspace_id: str | None = None) -> int: ...
    async def total_size(self, workspace_id: str | None = None) -> int: ...
    async def sessions(self, workspace_id: str | None = None) -> list[str]: ...


__all__ = ["CandidateBufferProtocol"]
